version: '3.7'
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
services:
    web:
        container_name: web
        build:
            context: ./httpd
        ports:
            - 8877:80
        networks:
            - frontend
            - backend
    php:
        container_name: php
        build:
            context: ./php
        working_dir: /srv/app
        networks:
            - backend
    mysql:
        container_name: db
        build:
            context: ./mysql
            
        volumes:
            - ../logs/mysql:${MYSQL_LOG_DIR}
            - ../database:/var/log/mysql
        networks:
            public_net:
                ipv4_address: ${MYSQL_IP}
        environment:
            - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
            - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}