version: '3.7'
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
services:
    web:
        container_name: web
        build:
            context: ./httpd
        ports:
            - 8877:80
        networks:
            - frontend
            - backend
    php:
        container_name: php
        build:
            context: ./php
        working_dir: /srv/app
        networks:
            - backend
    mysql:
        container_name: db
        build:
            context: ./mysql
        environment:
            - MYSQL_ROOT_PASSWORD=toor    
        volumes:
            - ./database:/var/log/mysql
        networks:
            - backend
        